<a href="https://colab.research.google.com/github/RAGHUKALLI/upgrade/blob/master/Day14_15_LetsUpgradeAIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a 3x3x3 array with random values

In [ ]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.05118797 0.82572644 0.96723344]
  [0.06574133 0.487248   0.70519428]
  [0.87359271 0.37565209 0.42028387]]

 [[0.19344057 0.84551086 0.18135276]
  [0.65575591 0.26579292 0.51015882]
  [0.74816628 0.69964873 0.88592659]]

 [[0.98053081 0.39678116 0.64023321]
  [0.03660196 0.87441967 0.12611283]
  [0.71555234 0.23095887 0.43029802]]]


2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
In [ ]:


In [ ]:
a = np.diag(1+np.arange(4), k = -1)
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np
b = np.ones((4,4))
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4.Normalize a 5x5 random matrix

In [ ]:
import numpy as np
c= np.random.random((5,5))
print("The original array is: ")
print(c)
cmax, cmin = c.max(), c.min()
c = (c - cmin)/(cmax - cmin)
print("\nThe array after normalization is: ")
print(c)

The original array is: 
[[0.14640134 0.05844455 0.24613188 0.97664098 0.09168169]
 [0.28305388 0.96986704 0.6159303  0.74065361 0.09597891]
 [0.27324991 0.77356062 0.03147433 0.87804334 0.23969899]
 [0.46077376 0.8665909  0.71343468 0.30422681 0.01615327]
 [0.11924728 0.16666405 0.40000168 0.7945661  0.99095425]]

The array after normalization is: 
[[0.13361504 0.04338454 0.23592366 0.98531673 0.07748086]
 [0.2738001  0.97836768 0.61528152 0.74322899 0.08188917]
 [0.2637427  0.77698666 0.01571712 0.8841703  0.22932448]
 [0.45611412 0.8724218  0.71530643 0.29552037 0.        ]
 [0.10575904 0.15440155 0.39377106 0.79853513 1.        ]]


5.How to find common values between two arrays?

In [ ]:
import numpy as np
arr1 = np.array([3,6,9,12,15,18,21,24,27,30])
type(arr1)
print("Array 1 is: ",arr1)
print()
arr2 = np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30])
print("Array 2 is: ",arr2)
print()
print("Common values between two arrays are:",np.intersect1d(arr1, arr2))

Array 1 is:  [ 3  6  9 12 15 18 21 24 27 30]

Array 2 is:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]

Common values between two arrays are: [ 6 12 18 24 30]



6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
import datetime as dt
today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-25
Today :  2020-07-26
Tomorrow :  2020-07-27


7.Consider two random array A and B, check if they are equal

In [ ]:
import numpy as np
a = np.random.randint(0,2,6)
print("Array A :",a)
print()
b = np.random.randint(0,2,6)
print("Array B :",b)
print()
print("Are the above arrays equal?")
arr_equal = np.allclose(a, b)
if arr_equal==True:
  print("Yes, the above arrays are equal")
else:
  print("No, the above arrays are not equal")

Array A : [0 0 0 1 1 1]

Array B : [1 0 0 0 1 1]

Are the above arrays equal?
No, the above arrays are not equal



8.Create random vector of size 10 and replace the maximum value by 0

In [ ]:
import numpy as np
a = np.random.rand(10)
print("The original array is:")
print(a)
print()
a[a.argmax()]=0
print("Array with maximum value replaced by 0 is:")
print(a)

The original array is:
[0.08473493 0.30919865 0.63285779 0.04198144 0.73046877 0.66899805
 0.05640031 0.28029445 0.88542637 0.38681929]

Array with maximum value replaced by 0 is:
[0.08473493 0.30919865 0.63285779 0.04198144 0.73046877 0.66899805
 0.05640031 0.28029445 0.         0.38681929]


9.How to print all the values of an array?

In [ ]:
from array import *

arr = array('i', [2,4,6,8,10,12,14,16])
print("The given array is: ",arr)
print("\nThe values of the array are as below:")
for i in arr:
 print(i)

The given array is:  array('i', [2, 4, 6, 8, 10, 12, 14, 16])

The values of the array are as below:
2
4
6
8
10
12
14
16



10.Subtract the mean of each row of a matrix

In [ ]:
import numpy as np
print("Original matrix:")
a = np.random.rand(2,3)
print(a)

print("\nSubtract the mean of each row of above matrix:")
b = a - a.mean(axis=1, keepdims=True)
print(b)

Original matrix:
[[0.69876563 0.02975815 0.14108638]
 [0.29597582 0.21196819 0.84593278]]

Subtract the mean of each row of above matrix:
[[ 0.40889558 -0.2601119  -0.14878367]
 [-0.15531644 -0.23932407  0.39464052]]



11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [28]:
a = np.ones(10) # need to check
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[2. 3. 4. 1. 6. 6. 3. 2. 2. 1.]



12.How to get the diagonal of a dot product?

In [43]:
# Solution1:Fast method
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print("Matrix A is:\n",A)
print("\nMatrix B is:\n",B)

C=np.dot(A,B)
print("\nDot Product of A&B is:\n",C)

D=np.einsum("ij,ji->i", A, B)
print("\nDiagonal of a dot product is:",D)

Matrix A is:
 [[2 6 5]
 [4 6 7]
 [6 8 0]]

Matrix B is:
 [[3 3 6]
 [1 6 0]
 [5 0 7]]

Dot Product of A&B is:
 [[37 42 47]
 [53 48 73]
 [26 66 36]]

Diagonal of a dot product is: [37 48 36]


In [45]:
# Solution2:Slow method
A=np.random.randint(0,10,(3,3))
B=np.random.randint(0,10,(3,3))

print("Matrix A is:\n",A)
print("\nMatrix B is:\n",B)

C=np.dot(A,B)
print("\nDot Product of A&B is:\n",C)

D=np.diag(np.dot(A, B))
print("\nDiagonal of a dot product is:",D)


Matrix A is:
 [[5 1 8]
 [8 4 8]
 [2 0 1]]

Matrix B is:
 [[3 1 0]
 [8 1 6]
 [4 6 0]]

Dot Product of A&B is:
 [[55 54  6]
 [88 60 24]
 [10  8  0]]

Diagonal of a dot product is: [55 60  0]


13.How to find the most frequent value in an array?

In [ ]:
# Solution1: Using numpy
import numpy as np
arr =[1,5,3,2,4,6,7,2,3,2,3,2]
print("Original array is:",arr)
print("\nMost frequent value in the above array is:",np.bincount(x).argmax())

Original array is: [1, 5, 3, 2, 4, 6, 7, 2, 3, 2, 3, 2]

Most frequent value in the above array is: 2


In [ ]:
# Solution2: Using statistics module
import statistics 
from statistics import mode 
arr=[1,5,3,2,4,6,7,2,3,2,3,2]
print("Original array is:",arr)
freq = mode(arr)
print("\nMost frequent value in the above array is",freq)

Original array is: [1, 5, 3, 2, 4, 6, 7, 2, 3, 2, 3, 2]

Most frequent value in the above array is 2



14.How to get the n largest values of an array

In [ ]:
import numpy as np
a =[12,20,11,25,9,7,8]
x=np.array(a)
print("Given original array is:",x)
n = 4
print ("\nThe largest values of the array are:",x[np.argsort(x)[-n:]])

Given original array is: [12 20 11 25  9  7  8]

The largest values of the array are: [11 12 20 25]


15.How to create a record array from a regular array?

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array(['cat','dog','horse','rabbit'])
arr3=np.array([15.30,21.56,34.89,27.51])
res= np.core.records.fromarrays([arr1, arr2, arr3],names='a,b,c')
print(res[0])
print(res[1])
print(res[2])

(1, 'cat', 15.3)
(2, 'dog', 21.56)
(3, 'horse', 34.89)
